[tox]
envlist = py313,docs
skipsdist = true

[testenv]
deps =
    -r{toxinidir}/requirements.txt
commands =
    pytest -q

[testenv:docs]
deps =
    -r{toxinidir}/requirements.txt
commands =
    sphinx-build -b html docs docs/_build/html -W
